version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build Docker image
      - run: 
          name: build
          command: docker build -t cigroup/gazebo:$CIRCLE_BRANCH .
      
      # push Docker image
      - run:
          name: push docker image
          command: |
            set -e
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cigroup/gazebo:$CIRCLE_BRANCH