version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-stretch-node
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # CACHE LOAD
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1-
          paths:
            - ~/caches/gazebo.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/caches/gazebo.tar | true

      # BUILD IMAGE
      - run:
          name: Build Gazebo image
          command: docker build --cache-from=app -t cigroup/gazebo:${CIRCLE_BRANCH//\//_} .

      # CACHE SAVE
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/gazebo.tar cigroup/gazebo:${CIRCLE_BRANCH//\//_}
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/caches/gazebo.tar

      # DEPLOY IMAGE
      - run:
          name: Push Gazebo image
          command: |
            set -e
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cigroup/gazebo:${CIRCLE_BRANCH//\//_}
