version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-stretch-node
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Gazebo image
          command: docker build -t cigroup/gazebo:$CIRCLE_BRANCH .
      
      - run:
          name: Push Gazebo image
          command: |
            set -e
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push cigroup/gazebo:$CIRCLE_BRANCH
